### ISSUE TITLE
Can you post a requirements.txt file?

### ISSUE THREAD

**Issue by amoldwin** [chihkuanyeh/concept_exp#1]
Hi Chih-Kuan, I would like to run your Concept Explanation code on the IMDB datasets, and try some experiments with other text datasets. Is there any chance you have a requirements file with the necessary versions of Python libraries needed to run your code?  I was running into some issues with the Tensorflow and Keras versions I am using.

**Comment by chihkuanyeh** [comment]
Hi sorry for the late reply, I've tried to add some requirements in my conda environment, hope this helps.
