### ISSUE TITLE
Problems visualizing the nearest neighbors in toy_topicmodel_main.py

### ISSUE THREAD

**Issue by nnnfffkkk** [chihkuanyeh/concept_exp#3]
Hello Chih Kuan,

I am having some issues running the provided toy example code.

1. May you clarify what the file 'toy_data/x_data_small.npy' in line 116 of toy_topicmodel_main.py is supposed to be? I am trying to run the toy example but it's giving me an error there that the file does not exist. Is it the same file as 'x_data.npy' created from the 60000 generated data? Or it needs to be generated separately?

2. I'm experiencing FileNotFoundError: [Errno 2] No such file or directory: '/volume00/jason/concept_stm/work_toy_test/concept_full_0_0.png'. May you clarify what these files are?

Thank you!

**Comment by chihkuanyeh** [comment]
Hi @nodenskoren, I think x_data_small.npy is just a file that includes the top 10000 entries of x_data, since loading x_data.npy is too memory consuming. As you can see we only find nearest neighbors of the top 10000 entries in line 117.

For your second question, which file generates this error?

**Comment by nnnfffkkk** [comment]
Hi @chihkuanyeh, thanks for the clarification. For the second question, I think it's lines 128 and 129 of the toy_topicmodel_main.py file, but I managed to get it fixed!
